src/main/java/com/rudolfschmidt/projectmanager/presentation/AcctounVerificationBean.java
/*
 * Copyright (C) 2014 Treehouse
 */
package com.rudolfschmidt.projectmanager.presentation;

import com.rudolfschmidt.projectmanager.business.UserAccountActivator;
import javax.enterprise.inject.Model;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Inject;

/**
 *
 * @author Rudolf Schmidt <mail@rudolfschmidt.com>
 */
@Model
public class AcctounVerificationBean {

    @Inject
    private UserAccountActivator userAccountActivator;
    private String verificationKey;

    public String getVerificationKey() {
        return verificationKey;
    }

    public void setVerificationKey(String verificationKey) {
        this.verificationKey = verificationKey;
    }

    public void validateKey() {
        final FacesContext currentInstance = FacesContext.getCurrentInstance();
        if (userAccountActivator.activateUserAccount(verificationKey)) {
            currentInstance.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO,
                    "Thank you! ",
                    "Your email has been verified."));
        } else {
            currentInstance.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR,
                    "Your activation key is invalid",
                    "Your email could not be verified"));
        }
    }
}

src/main/java/com/rudolfschmidt/projectmanager/presentation/FeedbackBean.java
/*
 * Copyright (C) 2013 Treehouse
 */
package com.rudolfschmidt.projectmanager.presentation;

import com.rudolfschmidt.projectmanager.business.mailer.FeedbackMailer;
import javax.enterprise.inject.Model;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.mail.MessagingException;

/**
 *
 * @author Rudolf Schmidt <mail@rudolfschmidt.com>
 */
@Model
public class FeedbackBean
{
    @Inject
    private FeedbackMailer feedbackProcessor;
    private int rating;
    private String message;

    public void submit()
    {
        final FacesContext currentInstance = FacesContext.getCurrentInstance();
        try {
            feedbackProcessor.sendFeedback(message, rating);
            final FacesMessage facesMessage = new FacesMessage("Your message was sent!", "we will answer as soon as possible!");
            currentInstance.addMessage(null, facesMessage);
        } catch (MessagingException ex) {
            currentInstance.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_WARN, ex.getMessage(), ex.getMessage()));
        }
    }

    public int getRating()
    {
        return rating;
    }

    public void setRating(int rating)
    {
        this.rating = rating;
    }

    public String getMessage()
    {
        return message;
    }

    public void setMessage(String message)
    {
        this.message = message;
    }

}

src/main/java/com/rudolfschmidt/projectmanager/presentation/NewPasswordBean.java
/*
 * Copyright (C) 2014 Treehouse
 */
package com.rudolfschmidt.projectmanager.presentation;

import com.rudolfschmidt.projectmanager.business.HashKey;
import com.rudolfschmidt.projectmanager.business.NewUserPasswordSetter;
import java.io.Serializable;
import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;
import javax.validation.constraints.Size;

/**
 *
 * @author Rudolf Schmidt <mail@rudolfschmidt.com>
 */
@Named
@SessionScoped
public class NewPasswordBean implements Serializable {

    @Inject
    private HashKey hashKeyValidator;
    @Inject
    private NewUserPasswordSetter newUserPasswordProcessor;
    @Size(min = 5, max = 50)
    private String password;
    @Size(min = 5, max = 50)
    private String confirmationPassword;
    private String verificationKey;
    private boolean keyValid;

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getConfirmationPassword() {
        return confirmationPassword;
    }

    public void setConfirmationPassword(String confirmationPassword) {
        this.confirmationPassword = confirmationPassword;
    }

    public String getVerificationKey() {
        return verificationKey;
    }

    public void setVerificationKey(String verificationKey) {
        this.verificationKey = verificationKey;
    }

    public boolean isKeyValid() {
        return keyValid;
    }

    public String action() {
        final FacesContext currentInstance = FacesContext.getCurrentInstance();
        if (newUserPasswordProcessor.setNewUserPassword(verificationKey, password)) {
            final FacesMessage facesMessage = new FacesMessage("New Password is accepted", "You can use your new password now");
            currentInstance.addMessage(null, facesMessage);
        } else {
            final FacesMessage facesMessage = new FacesMessage(FacesMessage.SEVERITY_FATAL, "Some error happen", "user not found");
            currentInstance.addMessage(null, facesMessage);
        }
        return null;
    }

    public void validateKey() {
        if (hashKeyValidator.validateUserHashKey(verificationKey)) {
            keyValid = true;
        } else {
            final FacesContext currentInstance = FacesContext.getCurrentInstance();
            final FacesMessage facesMessage = new FacesMessage(FacesMessage.SEVERITY_FATAL,
                    "Key is invalid",
                    "You cant change your password.");
            currentInstance.addMessage(null, facesMessage);
            keyValid = false;
        }
    }
}

src/main/java/com/rudolfschmidt/projectmanager/presentation/login/ContributionsBean.java
/*
 * Copyright (C) 2014 Treehouse
 */
package com.rudolfschmidt.projectmanager.presentation.login;

import com.rudolfschmidt.projectmanager.business.core.ContributionProcessor;
import com.rudolfschmidt.projectmanager.business.exceptions.ForbiddenOperationException;
import com.rudolfschmidt.projectmanager.persistence.Contribution;
import java.util.List;
import javax.enterprise.inject.Model;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Inject;

/**
 *
 * @author Rudolf Schmidt <mail@rudolfschmidt.com>
 */
@Model
public class ContributionsBean {

    @Inject
    ContributionProcessor contributionProcessor;
    @Inject
    TopicBean topicBean;
    String content;

    public void create() {
        try {
            contributionProcessor.create(topicBean.getTopic(), content);
        } catch (ForbiddenOperationException ex) {
            final FacesMessage facesMessage1 = new FacesMessage(FacesMessage.SEVERITY_WARN, ex.getMessage(), ex.getMessage());
            FacesContext.getCurrentInstance().addMessage(null, facesMessage1);
        }
        content = null;
    }

    public List<Contribution> getContributions() {
        return contributionProcessor.getContributions(topicBean.getTopic());
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

}

src/main/java/com/rudolfschmidt/projectmanager/presentation/login/NewProjectBean.java
/*
 * Copyright (C) 2014 Treehouse
 */
package com.rudolfschmidt.projectmanager.presentation.login;

import com.rudolfschmidt.projectmanager.business.core.ProjectProcessor;
import com.rudolfschmidt.projectmanager.business.exceptions.InvalidTitleException;
import javax.enterprise.inject.Model;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Inject;

/**
 *
 * @author Rudolf Schmidt <mail@rudolfschmidt.com>
 */
@Model
public class NewProjectBean {

    @Inject
    ProjectProcessor projectProcessor;

    String title;

    public void create() {
        try {
            projectProcessor.create(title);
        } catch (InvalidTitleException ex) {
            final FacesMessage facesMessage1 = new FacesMessage(FacesMessage.SEVERITY_WARN, ex.getClass().getSimpleName(), ex.getMessage());
            FacesContext.getCurrentInstance().addMessage(null, facesMessage1);
        }
        title = null;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

}

src/main/java/com/rudolfschmidt/projectmanager/presentation/login/NewProjectLeaderBean.java
/*
 * Copyright (C) 2014 Treehouse
 */
package com.rudolfschmidt.projectmanager.presentation.login;

import com.rudolfschmidt.projectmanager.business.core.ProjectProcessor;
import com.rudolfschmidt.projectmanager.business.exceptions.ForbiddenOperationException;
import com.rudolfschmidt.projectmanager.persistence.OneUser;
import java.io.Serializable;
import java.util.List;
import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;

/**
 *
 * @author Rudolf Schmidt <mail@rudolfschmidt.com>
 */
@Named
@SessionScoped
public class NewProjectLeaderBean implements Serializable {

    @Inject
    ProjectProcessor projectProcessor;
    @Inject
    ProjectBean projectBean;
    OneUser[] selectedLeaders;

    public void add() {
        for (OneUser user : selectedLeaders) {
            try {
                projectProcessor.addLeader(projectBean.getProject(), user);
            } catch (ForbiddenOperationException ex) {
                final FacesMessage facesMessage = new FacesMessage(FacesMessage.SEVERITY_WARN, ex.getClass().getSimpleName(), ex.getMessage());
                FacesContext.getCurrentInstance().addMessage(null, facesMessage);
            }
        }
        selectedLeaders = null;
    }

    public List<OneUser> getLeaders() {
        return projectProcessor.getAvailableLeaders(projectBean.getProject());
    }

    public OneUser[] getSelectedLeaders() {
        return selectedLeaders;
    }

    public void setSelectedLeaders(OneUser[] selectedLeaders) {
        this.selectedLeaders = selectedLeaders;
    }

}

src/main/java/com/rudolfschmidt/projectmanager/presentation/login/NewProjectMemberBean.java
/*
 * Copyright (C) 2014 Treehouse
 */
package com.rudolfschmidt.projectmanager.presentation.login;

import com.rudolfschmidt.projectmanager.business.core.ProjectProcessor;
import com.rudolfschmidt.projectmanager.business.exceptions.ForbiddenOperationException;
import com.rudolfschmidt.projectmanager.persistence.OneUser;
import java.io.Serializable;
import java.util.List;
import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;

/**
 *
 * @author Rudolf Schmidt <mail@rudolfschmidt.com>
 */
@Named
@SessionScoped
public class NewProjectMemberBean implements Serializable {

    @Inject
    ProjectProcessor projectProcessor;
    @Inject
    ProjectBean projectBean;
    OneUser[] selectedMembers;

    public void add() {
        for (OneUser user : selectedMembers) {
            try {
                projectProcessor.addMember(projectBean.getProject(), user);
            } catch (ForbiddenOperationException ex) {
                final FacesMessage facesMessage = new FacesMessage(FacesMessage.SEVERITY_WARN, ex.getClass().getSimpleName(), ex.getMessage());
                FacesContext.getCurrentInstance().addMessage(null, facesMessage);
            }
        }
        selectedMembers = null;
    }

    public List<OneUser> getMembers() {
        return projectProcessor.getAvailableMembers(projectBean.getProject());
    }

    public OneUser[] getSelectedMembers() {
        return selectedMembers;
    }

    public void setSelectedMembers(OneUser[] selectedMembers) {
        this.selectedMembers = selectedMembers;
    }

}

src/main/java/com/rudolfschmidt/projectmanager/presentation/login/NewProjectTopicBean.java
/*
 * Copyright (C) 2014 Treehouse
 */
package com.rudolfschmidt.projectmanager.presentation.login;

import com.rudolfschmidt.projectmanager.business.core.TopicProcessor;
import com.rudolfschmidt.projectmanager.business.exceptions.ForbiddenOperationException;
import com.rudolfschmidt.projectmanager.business.exceptions.InvalidTitleException;
import javax.enterprise.inject.Model;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Inject;

/**
 *
 * @author Rudolf Schmidt <mail@rudolfschmidt.com>
 */
@Model
public class NewProjectTopicBean {

    @Inject
    ProjectBean projectBean;
    @Inject
    TopicProcessor topicProcessor;
    String title;

    public void create() {
        try {
            topicProcessor.create(projectBean.getProject(), title);
        } catch (InvalidTitleException ex) {
            final FacesMessage facesMessage = new FacesMessage(FacesMessage.SEVERITY_WARN, ex.getClass().getSimpleName(), ex.getMessage());
            FacesContext.getCurrentInstance().addMessage(null, facesMessage);
        } catch (ForbiddenOperationException ex) {
            final FacesMessage facesMessage = new FacesMessage(FacesMessage.SEVERITY_WARN, ex.getClass().getSimpleName(), ex.getMessage());
            FacesContext.getCurrentInstance().addMessage(null, facesMessage);
        }
        title = null;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

}

src/main/java/com/rudolfschmidt/projectmanager/presentation/login/NewTopicBean.java
/*
 * Copyright (C) 2014 Treehouse
 */
package com.rudolfschmidt.projectmanager.presentation.login;

import com.rudolfschmidt.projectmanager.business.core.ProjectProcessor;
import com.rudolfschmidt.projectmanager.business.core.TopicProcessor;
import com.rudolfschmidt.projectmanager.business.exceptions.ForbiddenOperationException;
import com.rudolfschmidt.projectmanager.business.exceptions.InvalidTitleException;
import com.rudolfschmidt.projectmanager.persistence.Project;
import java.util.List;
import javax.enterprise.inject.Model;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Inject;

/**
 *
 * @author Rudolf Schmidt <mail@rudolfschmidt.com>
 */
@Model
public class NewTopicBean {

    @Inject
    ProjectProcessor projectProcessor;
    @Inject
    TopicProcessor topicProcessor;
    String title;
    long projectId;

    public void create() {
        try {
            topicProcessor.create(projectId, title);
        } catch (InvalidTitleException ex) {
            final FacesMessage facesMessage = new FacesMessage(FacesMessage.SEVERITY_WARN, ex.getClass().getSimpleName(), ex.getMessage());
            FacesContext.getCurrentInstance().addMessage(null, facesMessage);
        } catch (ForbiddenOperationException ex) {
            final FacesMessage facesMessage = new FacesMessage(FacesMessage.SEVERITY_WARN, ex.getClass().getSimpleName(), ex.getMessage());
            FacesContext.getCurrentInstance().addMessage(null, facesMessage);
        }
        title = null;
    }

    public List<Project> getProjects() {
        return projectProcessor.getProjects();
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public long getProjectId() {
        return projectId;
    }

    public void setProjectId(long projectId) {
        this.projectId = projectId;
    }

}

src/main/java/com/rudolfschmidt/projectmanager/presentation/login/TopicsBean.java
/*
 * Copyright (C) 2014 Treehouse
 */
package com.rudolfschmidt.projectmanager.presentation.login;

import com.rudolfschmidt.projectmanager.business.core.TopicProcessor;
import com.rudolfschmidt.projectmanager.business.exceptions.ForbiddenOperationException;
import com.rudolfschmidt.projectmanager.persistence.Topic;
import java.io.Serializable;
import java.util.List;
import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;

/**
 *
 * @author Rudolf Schmidt <mail@rudolfschmidt.com>
 */
@Named
@SessionScoped
public class TopicsBean implements Serializable {

    @Inject
    ProjectBean projectBean;
    @Inject
    TopicProcessor topicProcessor;
    Topic[] selectedTopics;

    public void remove() {
        for (Topic topic : selectedTopics) {
            try {
                topicProcessor.remove(topic);
            } catch (ForbiddenOperationException ex) {
                final FacesMessage facesMessage = new FacesMessage(FacesMessage.SEVERITY_WARN, ex.getClass().getSimpleName(), ex.getMessage());
                FacesContext.getCurrentInstance().addMessage(null, facesMessage);
            }
        }
        selectedTopics = null;
    }

    public String edit() {
        final long id = selectedTopics[0].getId();
        selectedTopics = null;
        return "topic?faces-redirect=true&id=" + id;
    }

    public List<Topic> getTopics() {
        return topicProcessor.getTopics(projectBean.getProjectId());
    }

    public List<Topic> getAllTopics() {
        return topicProcessor.getTopics();
    }

    public Topic[] getSelectedTopics() {
        return selectedTopics;
    }

    public void setSelectedTopics(Topic[] selectedTopics) {
        this.selectedTopics = selectedTopics;
    }

}

src/main/webapp/accountVerification.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                template="./resources/templates/basic.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui">

    <ui:define name="basic">
        <f:metadata>
            <f:viewParam name="key" value="#{acctounVerificationBean.verificationKey}"/>
            <f:event type="preRenderView" listener="#{acctounVerificationBean.validateKey()}"/>
        </f:metadata>
        <p:messages autoUpdate="true" showDetail="true"/>
    </ui:define>
</ui:composition>

src/main/webapp/feedback.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                template="./resources/templates/navigation.xhtml"
                xmlns:p="http://primefaces.org/ui"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:define name="content">
        <h:form>
            <p:breadCrumb>
                <p:menuitem value="Home" outcome="index" />
                <p:menuitem value="Feedback" outcome="feedback" />
            </p:breadCrumb>
        </h:form>
        <p>
            Send us your feedback.
        </p>
        <h:form>
            <p:messages id="messages" showDetail="false" />
            <p:panelGrid id="grid" columns="2" columnClasses="feedbackFormular">
                <f:facet name="header">
                    Feedback Dialog
                </f:facet>
                <p:outputLabel for="rating" value="Rating:" />
                <p:rating id="rating" value="#{feedbackBean.rating}" required="true" />
                <p:outputLabel for="message" value="Your Message:" />
                <p:inputTextarea id="message" cols="60" rows="10" required="true" value="#{feedbackBean.message}" />
                <f:facet name="footer">
                    <p:commandButton value="Submit" action="#{feedbackBean.submit}" update="grid,messages"/>
                </f:facet>
            </p:panelGrid>
        </h:form>
    </ui:define>

</ui:composition>

src/main/webapp/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                template="./resources/templates/logout.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:p="http://primefaces.org/ui">

    <ui:define name="logout">
        <p:tabView id="view">
            <p:tab id="tab" title="Login">
                <h:form>
                    <p:messages id="messages" showDetail="true" />
                    <p:panelGrid id="grid" columns="3">
                        <f:facet name="header">Login</f:facet>
                        <p:outputLabel for="email" value="Email:" />
                        <p:inputText id="email" value="#{loginBean.email}" required="true" />
                        <p:message for="email"/>

                        <p:outputLabel for="password" value="Password:" />
                        <p:password id="password" value="#{loginBean.password}" required="true" />
                        <p:message for="password"/>

                        <f:facet name="footer">
                            <p:commandButton id="loginButton" value="Submit" action="#{loginBean.login}" update="grid,messages" />
                        </f:facet>
                    </p:panelGrid>
                </h:form>
            </p:tab>
            <p:tab title="Registration">
                <h:form>
                    <p:messages showDetail="true"/>
                    <p:panelGrid id="grid" columns="3">
                        <f:facet name="header">
                            Registration
                        </f:facet>
                        <p:outputLabel for="prename" value="Prename:" />
                        <p:inputText id="prename" value="#{registrationBean.prename}" label="prename" required="true" />
                        <p:message for="prename" />
                        <p:outputLabel for="surname" value="Surname:" />
                        <p:inputText id="surname" value="#{registrationBean.surname}" required="true" />
                        <p:message for="surname"/>
                        <p:outputLabel for="email" value="Email:" />
                        <p:inputText id="email" value="#{registrationBean.email}" required="true" />
                        <p:message for="email"/>
                        <p:outputLabel for="password" value="Password:" />
                        <p:password id="password" value="#{registrationBean.password}" feedback="true" required="true" />
                        <p:message for="password"/>
                        <p:outputLabel for="conditions" value="Accept Conditions:" />
                        <p:selectBooleanButton id="conditions" value="#{registrationBean.conditions}" onLabel="Yes" offLabel="No" required="true"/>
                        <p:message for="conditions"/>
                        <f:facet name="footer">
                            <p:commandButton value="Submit" action="#{registrationBean.action}" update="@form"/>
                        </f:facet>
                    </p:panelGrid>
                </h:form>
            </p:tab>
            <p:tab title="Request Password">
                <h:form>
                    <p:messages showDetail="true"/>
                    <p:panelGrid id="grid" columns="3">
                        <f:facet name="header">
                            Request password
                        </f:facet>
                        <p:outputLabel for="email" value="Email:" />
                        <p:inputText id="email" value="#{requestPasswordBean.email}" required="true" />
                        <p:message for="email"/>
                        <f:facet name="footer">
                            <p:commandButton value="Submit" action="#{requestPasswordBean.action}" update="@form"/>
                        </f:facet>
                    </p:panelGrid>
                </h:form>
            </p:tab>
        </p:tabView>
    </ui:define>

</ui:composition>

src/main/webapp/newPassword.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                template="./resources/templates/basic.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui">


    <ui:define name="basic">
        <f:metadata>
            <f:viewParam name="key" value="#{newPasswordBean.verificationKey}"/>
            <f:event type="preRenderView" listener="#{newPasswordBean.validateKey()}"/>
        </f:metadata>

        <p:messages autoUpdate="true" showDetail="true"/>
        <h:form>
            <p:panelGrid id="grid" columns="3" rendered="#{newPasswordBean.keyValid}">
                <f:facet name="header">
                    Enter new password
                </f:facet>
                <p:outputLabel for="password" value="New Password:" />
                <p:password id="password" value="#{newPasswordBean.password}" match="confirmationPassword" feedback="true" required="true" />
                <p:message for="password"/>
                <p:outputLabel for="confirmationPassword" value="Confirm Password:" />
                <p:password id="confirmationPassword" value="#{newPasswordBean.confirmationPassword}" feedback="true" required="true" />
                <p:message for="confirmationPassword"/>
                <f:facet name="footer">
                    <p:commandButton value="Submit" action="#{newPasswordBean.action}" update="grid" />
                </f:facet>
            </p:panelGrid>
        </h:form>
    </ui:define>


</ui:composition>

src/main/webapp/topics.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                template="/resources/templates/navigation.xhtml"
                xmlns:p="http://primefaces.org/ui"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:define name="breadcrumb">
        <h:form>
            <p:breadCrumb>
                <p:menuitem value="Home" outcome="index" />
                <p:menuitem value="Topics" outcome="topics" />
            </p:breadCrumb>
        </h:form>
    </ui:define>

    <ui:define name="dialog">
        <p:dialog widgetVar="newTopicDialog" header="New Topic" modal="true">
            <h:form>
                <p:panelGrid columns="2">
                    <p:outputLabel for="title" value="Topic Title:"/>
                    <p:inputText id="title" value="#{newTopicBean.title}" required="true"/>
                    <p:outputLabel for="project" value="Parent Project:"/>
                    <p:selectOneMenu id="project" value="#{newTopicBean.projectId}" effect="fade">
                        <f:selectItems value="#{newTopicBean.projects}" var="project" itemLabel="#{project.title}" itemValue="#{project.id}"/>
                    </p:selectOneMenu>
                    <f:facet name="footer">
                        <p:commandButton value="OK" action="#{newTopicBean.create}" update="@form,:form" oncomplete="PF('newTopicDialog').hide();"/>
                        <p:commandButton value="Cancel" onclick="PF('newTopicDialog').hide();"/>
                    </f:facet>
                </p:panelGrid>
            </h:form>
        </p:dialog>
    </ui:define>

    <ui:define name="content">
        <h:form id="form">
            <p:messages showDetail="true"/>
            <p:dataTable value="#{topicsBean.allTopics}" var="topic"
                         rowKey="#{topic.id}" selection="#{topicsBean.selectedTopics}" selectionMode="multiple">

                <p:ajax event="rowSelect" update="@form" />
                <p:ajax event="rowUnselect" update="@form" />

                <f:facet name="header">Topics</f:facet>

                <p:column>
                    <f:facet name="header">Title</f:facet>
                    <h:outputText value="#{topic.title}"/>
                </p:column>

                <p:column>
                    <f:facet name="header">State</f:facet>
                    <h:outputText value="#{topic.closed?'closed':'open'}"/>
                </p:column>

                <p:column>
                    <f:facet name="header">Owner</f:facet>
                    <h:outputText value="#{topic.owner.email}"/>
                </p:column>

                <p:column>
                    <f:facet name="header">Project</f:facet>
                    <h:outputText value="#{topic.project.title}"/>
                </p:column>

                <f:facet name="footer">
                    <div style="text-align: left">
                        <p:commandButton icon="ui-icon-plus" value="New" onclick="PF('newTopicDialog').show();"/>
                        <p:commandButton value="Edit"
                                         action="#{topicsBean.edit}"
                                         disabled="#{empty topicsBean.selectedTopics}"
                                         update="@form"
                                         icon="ui-icon-folder-open"/>
                        <p:commandButton value="Remove"
                                         action="#{topicsBean.remove}"
                                         disabled="#{empty topicsBean.selectedTopics}"
                                         update="@form"
                                         icon="ui-icon-trash"/>
                    </div>
                </f:facet>
            </p:dataTable>
        </h:form>
    </ui:define>

</ui:composition>